# ===================================================================
# Database Configuration
# ===================================================================
db.url= jdbc:mysql://localhost:3306/poker_db
db.username=root
db.password=11X.gjiaDB
db.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool Settings (Optional, for performance tuning)
db.pool.max-active=10
db.pool.initial-size=2